# Generated by Django 5.0.14 on 2026-09-28 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0003_athlete_user'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recorded_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='athletes.athlete')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='clubs.club')),
            ],
        ),
    ]
