# Generated by Django 5.0.14 on 2026-09-28 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0002_initial'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('opponent_name', models.CharField(blank=True, max_length=200)),
                ('fight_date', models.DateField(blank=True, null=True)),
                ('event', models.CharField(blank=True, max_length=200)),
                ('competition_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('result', models.CharField(blank=True, choices=[('WIN', 'Victoria'), ('LOSS', 'Derrota'), ('DRAW', 'Empate')], max_length=20)),
                ('fight_type', models.CharField(blank=True, choices=[('AMATEUR', 'Amateur'), ('PRO', 'Profesional'), ('SPARRING', 'Sparring')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fight_records', to='athletes.athlete')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='clubs.club')),
            ],
            options={
                'ordering': ['-fight_date', '-competition_date', '-created_at'],
                'indexes': [models.Index(fields=['club', 'athlete'], name='competition_club_id_5165b9_idx'), models.Index(fields=['athlete', 'fight_date'], name='competition_athlete_b758b7_idx')],
            },
        ),
    ]
