# Generated by Django 5.0.14 on 2026-09-28 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('activity_type', models.CharField(choices=[('TECHNICAL', 'Técnica'), ('TACTICAL', 'Táctica'), ('PHYSICAL', 'Acondicionamiento físico'), ('SPARRING', 'Sparring'), ('COMPETITION', 'Preparación competitiva')], default='TECHNICAL', max_length=30)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programado'), ('CANCELLED', 'Cancelado'), ('COMPLETED', 'Completado')], default='SCHEDULED', max_length=20)),
                ('objectives', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='clubs.club')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='groups.group')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
