# Generated by Django 5.0.14 on 2026-09-28 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_athlete_user'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='capacity',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.CreateModel(
            name='TrainingReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RESERVED', 'Reservado'), ('CANCELLED', 'Cancelado')], default='RESERVED', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_reservations', to='athletes.athlete')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='trainings.training')),
            ],
            options={
                'indexes': [models.Index(fields=['training', 'status'], name='trainings_t_trainin_586cac_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='trainingreservation',
            constraint=models.UniqueConstraint(fields=('training', 'athlete'), name='unique_training_athlete_reservation'),
        ),
    ]
