# Generated by Django 5.0.14 on 2026-09-28 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='groups.group'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['club', 'status'], name='athletes_at_club_id_39ac18_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['group', 'assigned_trainer'], name='athletes_at_group_i_4487f4_idx'),
        ),
    ]
