# Generated by Django 5.0.14 on 2026-09-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_athlete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='is_competitor',
            field=models.BooleanField(default=False),
        ),
    ]
