# Generated by Django 5.0.14 on 2026-09-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('MERCADO_PAGO', 'Mercado Pago'), ('BANK_TRANSFER', 'Transferencia'), ('RESERVE', 'Reserva para retiro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagada'), ('READY', 'Lista para retirar'), ('COMPLETED', 'Retirada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=16),
        ),
    ]
