# Generated by Django 5.0.14 on 2026-09-28 20:50

import apps.store.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_storesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, storage=apps.store.models.private_payment_proof_storage, upload_to=apps.store.models.payment_proof_upload_path),
        ),
        migrations.AddField(
            model_name='order',
            name='proof_review_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='proof_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='proof_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_proofs_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='proof_status',
            field=models.CharField(choices=[('NOT_SUBMITTED', 'Sin comprobante'), ('SUBMITTED', 'En revisión'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='NOT_SUBMITTED', max_length=16),
        ),
    ]
