# Generated by Django 5.0.14 on 2026-09-28 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='trainings.training'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['club', 'status'], name='attendance__club_id_b73e23_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['training', 'status'], name='attendance__trainin_7f009c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('athlete', 'training')},
        ),
    ]
