# Generated by Django 5.0.14 on 2026-09-28 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0003_athlete_user'),
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField()),
                ('technical', models.PositiveSmallIntegerField(default=0)),
                ('defense', models.PositiveSmallIntegerField(default=0)),
                ('speed', models.PositiveSmallIntegerField(default=0)),
                ('endurance', models.PositiveSmallIntegerField(default=0)),
                ('power', models.PositiveSmallIntegerField(default=0)),
                ('coordination', models.PositiveSmallIntegerField(default=0)),
                ('mobility', models.PositiveSmallIntegerField(default=0)),
                ('general_condition', models.PositiveSmallIntegerField(default=0)),
                ('observations', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('improvement_areas', models.TextField(blank=True)),
                ('next_goals', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='athletes.athlete')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='clubs.club')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_done', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
